vich_uploader:
    db_driver: orm

    mappings:
        article_picture:
            uri_prefix: /uploads/articles
            upload_destination: '%kernel.project_dir%/public/uploads/articles'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
